### ISSUE TITLE
PCRaster 4.2 and Python 2- division not implemented for Field?

### ISSUE THREAD

**Issue by domeniconappo** [pcraster/pcraster#285]
Hi there,

I have a strange issue when testing our python PCRaster code with:

* PCRaster 4.2
* Python2.7

**EDIT**:
We import division from \_\_future\_\_ package: not sure how this can influence behaviour.
`from __future__ import print_function, absolute_import, division`
**END EDIT**

Basically, I'm not able to execute a division between PCRaster fields:

`LZTemp2/LZTemp3`

This raises:
`TypeError: unsupported operand type(s) for /: 'Field' and 'Field'`

I have to compute division in numpy which means I need conversions pcr2numpy and numpy2pcr:

`numpy2pcr(Scalar, pcr2numpy(LZTemp2, mv=-9999) / pcr2numpy(LZTemp3, mv=-9999), -9999))`

Am I doing anything wrong or any reason why it wasn't implemented for Python2?
The division was working fine with previous PCRaster versions.

Anyway, I noticed that floor division is implemented so this won't raise exceptions:
`LZTemp2//LZTemp3`

Using Python3.6 everything is fine.
Unfortunately, our code must be Python2/Python3 compatible until end of next year...

Many thanks in advance.
d

**Comment by OliverSchmitz** [comment]
we check the Python version and overload the / operator differently for 2.x and 3.x. I assume the overload conflicts/fails with your 'division' import from the future module, I guess the truediv (v3) is now required due to your future import instead of the div (v2)
you could do 
from pcraster.operators import pcrDiv
then pcrDiv(a,b) instead of a/b, that should work in any case but requires changing the script, but at least no conversion to numpy required

**Comment by domeniconappo** [comment]
Hi Oliver,
Thanks for the suggestion. It will help for sure

D.
